<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommonBatchFramework" Version="1.0.7" />
    <PackageReference Include="Google.Apis" Version="1.73.0" />
    <PackageReference Include="Google.apis.Auth" Version="1.73.0" />
    <PackageReference Include="Google.apis.Drive.v3" Version="1.73.0.4112" />
  </ItemGroup>

</Project>